# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailgun_events_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailgunevent',
            name='campaigns',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='client_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='delivery_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='envelope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='flags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='geolocation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='log_level',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='recipient_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='routes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='storage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mailgunevent',
            name='user_variables',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mailgunevent',
            name='json',
            field=models.TextField(blank=True, default=''),
        ),
    ]

